# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-14 04:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoKlinik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_klinik', models.CharField(max_length=50)),
                ('wilayah', models.CharField(max_length=50)),
                ('alamat', models.CharField(max_length=100)),
                ('no_telp', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='InfoPenyakit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_penyakit', models.CharField(max_length=30)),
                ('nama_lain_penyakit', models.CharField(max_length=50)),
                ('info_umum', models.TextField()),
                ('penyebab', models.TextField()),
                ('gejala', models.TextField()),
                ('treatment', models.TextField()),
                ('pencegahan', models.TextField()),
                ('peringatan', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kucing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kucing', models.CharField(max_length=30)),
                ('umur_kucing', models.CharField(max_length=10)),
                ('gender_kucing', models.CharField(choices=[('betina', 'Betina'), ('jantan', 'Jantan')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ListGejala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_gejala', models.CharField(max_length=5)),
                ('nama_gejala', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ListPenyakit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_penyakit', models.CharField(max_length=5)),
                ('nama_penyakit', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pemilik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('alamat', models.CharField(blank=True, max_length=250)),
                ('no_hp', models.CharField(blank=True, max_length=15)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('kucing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitederma.Kucing')),
            ],
        ),
    ]
