# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 04:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitederma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Konsultasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bobotcf', models.FloatField()),
                ('gejala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitederma.ListGejala')),
                ('penyakit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitederma.ListPenyakit')),
            ],
        ),
        migrations.CreateModel(
            name='ListPertanyaan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_pertanyaan', models.CharField(max_length=5)),
                ('pertanyaan', models.TextField()),
                ('gejala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitederma.ListGejala')),
            ],
        ),
    ]
