# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitederma', '0002_konsultasi_listpertanyaan'),
    ]

    operations = [
        migrations.AddField(
            model_name='konsultasi',
            name='kodecf',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
    ]
