# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitederma', '0003_konsultasi_kodecf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jawaban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodejawab', models.CharField(max_length=3)),
                ('jawab', models.TextField()),
                ('bobotjawab', models.FloatField()),
            ],
        ),
    ]
