# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-18 04:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitederma', '0007_auto_20170607_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListTanya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_tanya', models.CharField(max_length=5)),
                ('daftar_tanya', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='useractivationkey',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2017, 7, 18)),
        ),
    ]
