# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-30 16:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitederma', '0010_auto_20170727_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pemilik',
            name='kucing',
        ),
        migrations.RenameField(
            model_name='infopenyakit',
            old_name='treatment',
            new_name='pengobatan',
        ),
        migrations.RenameField(
            model_name='konsultasi',
            old_name='gejala',
            new_name='kode_gejala',
        ),
        migrations.RemoveField(
            model_name='infopenyakit',
            name='nama_lain_penyakit',
        ),
        migrations.RemoveField(
            model_name='konsultasi',
            name='penyakit',
        ),
        migrations.AddField(
            model_name='infopenyakit',
            name='kode_penyakit',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='konsultasi',
            name='kode_penyakit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sitederma.InfoPenyakit'),
        ),
        migrations.AlterField(
            model_name='useractivationkey',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2017, 7, 30)),
        ),
        migrations.DeleteModel(
            name='ListPenyakit',
        ),
        migrations.DeleteModel(
            name='Pemilik',
        ),
    ]
