# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-30 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitederma', '0011_auto_20170730_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopenyakit',
            name='kode_penyakit',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
