# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-30 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitederma', '0012_auto_20170730_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infopenyakit',
            name='info_penyakit_slug',
        ),
    ]
