# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-02 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitederma', '0015_auto_20170802_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoklinik',
            name='alamat',
            field=models.TextField(),
        ),
    ]
