# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-03 09:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitederma', '0016_auto_20170802_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivationkey',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2017, 8, 3)),
        ),
    ]
