# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-03 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitederma', '0017_auto_20170803_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='listtanya',
            name='no_tanya',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
