# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-13 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitederma', '0020_auto_20170813_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kucing',
            old_name='pemilik',
            new_name='username',
        ),
    ]
