# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-13 12:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sitederma', '0022_kucing_kode_kucing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Riwayat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_riwayat', models.CharField(max_length=3)),
                ('hasil_diagnosa', models.CharField(max_length=30)),
                ('kode_kucing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_kode_kucing', to='sitederma.Kucing')),
                ('nama_kucing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_nama_kucing', to='sitederma.Kucing')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_username', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
