# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-13 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitederma', '0023_riwayat'),
    ]

    operations = [
        migrations.AddField(
            model_name='riwayat',
            name='tanggal_diagnosa',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
