# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-14 02:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitederma', '0025_auto_20170813_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kucing',
            name='kode_kucing',
        ),
        migrations.AlterField(
            model_name='useractivationkey',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2017, 8, 14)),
        ),
    ]
