# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-14 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitederma', '0027_auto_20170814_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riwayat',
            name='kode_kucing',
        ),
        migrations.RemoveField(
            model_name='riwayat',
            name='kode_riwayat',
        ),
    ]
