# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-16 07:12
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitederma', '0028_auto_20170814_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kucing',
            name='umur_kucing',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='useractivationkey',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2017, 8, 16)),
        ),
    ]
